## Observação

O arquivo de teste `test_relatorio_1.py` deverá ser extraído para a pasta raiz do projeto para ser executado corretamente. Caso contrário, o seguinte erro será apresentado:

```bash
python tests/test_relatorio_1.py
Traceback (most recent call last):
    File "C:\Users\gonca\OneDrive\Área de Trabalho\IZE\Relatório Mensal\code\v2_relatorio_mensal\tests\test_relatorio_1.py", line 4, in <module>
        from src.database.db_utils import DatabaseConnection
ModuleNotFoundError: No module named 'src'
```

Posteriormente resolverei isso.